FROM node:20.17-alpine AS dist

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx AS prod-stage

COPY --from=dist /app/dist /usr/share/nginx/html
COPY --from=dist /app/default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]